-- Catalogs per environment. Agents write only to dev.
CREATE CATALOG IF NOT EXISTS mrs_dev;
CREATE CATALOG IF NOT EXISTS mrs_test;
CREATE CATALOG IF NOT EXISTS mrs_prod;

GRANT USE CATALOG, USE SCHEMA, SELECT, MODIFY, CREATE TABLE ON CATALOG mrs_dev TO `sp-aidlc-agents`;
GRANT USE CATALOG, USE SCHEMA, SELECT ON CATALOG mrs_test TO `sp-aidlc-agents`;
GRANT USE CATALOG, USE SCHEMA, SELECT ON CATALOG mrs_prod TO `sp-aidlc-agents`;

GRANT USE CATALOG, USE SCHEMA, SELECT, MODIFY, CREATE TABLE ON CATALOG mrs_test TO `sp-aidlc-ci`;
GRANT USE CATALOG, USE SCHEMA, SELECT, MODIFY, CREATE TABLE ON CATALOG mrs_prod TO `sp-aidlc-ci`;

GRANT USE CATALOG, USE SCHEMA, SELECT, MODIFY, CREATE TABLE ON CATALOG mrs_dev TO `data-science-team`;
GRANT USE CATALOG, USE SCHEMA, SELECT ON CATALOG mrs_prod TO `data-science-team`;
